package com.myspace.documentgenerator;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class criteriaASIC implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String product;
	private java.lang.String subProduct;
	private java.lang.String service;
	private java.lang.String subService;
	private java.lang.String region;
	private java.lang.String country;
	private java.lang.String audience;
	private java.lang.String subChannel;
	private java.lang.String residency;
	private java.lang.String entityTypes;
	private java.lang.String leDomicile;

	private java.lang.String documentName;

	private java.lang.String documentDesc;

	private java.lang.String documentCertification;

	private java.lang.String documentPolicy;

	private java.lang.String instructions;

	private java.lang.String documentTemplate;

	private java.lang.String documentGroup;

	public criteriaASIC() {
	}

	public java.lang.String getProduct() {
		return this.product;
	}

	public void setProduct(java.lang.String product) {
		this.product = product;
	}

	public java.lang.String getSubProduct() {
		return this.subProduct;
	}

	public void setSubProduct(java.lang.String subProduct) {
		this.subProduct = subProduct;
	}

	public java.lang.String getService() {
		return this.service;
	}

	public void setService(java.lang.String service) {
		this.service = service;
	}

	public java.lang.String getSubService() {
		return this.subService;
	}

	public void setSubService(java.lang.String subService) {
		this.subService = subService;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getAudience() {
		return this.audience;
	}

	public void setAudience(java.lang.String audience) {
		this.audience = audience;
	}

	public java.lang.String getSubChannel() {
		return this.subChannel;
	}

	public void setSubChannel(java.lang.String subChannel) {
		this.subChannel = subChannel;
	}

	public java.lang.String getResidency() {
		return this.residency;
	}

	public void setResidency(java.lang.String residency) {
		this.residency = residency;
	}

	public java.lang.String getEntityTypes() {
		return this.entityTypes;
	}

	public void setEntityTypes(java.lang.String entityTypes) {
		this.entityTypes = entityTypes;
	}

	public java.lang.String getLeDomicile() {
		return this.leDomicile;
	}

	public void setLeDomicile(java.lang.String leDomicile) {
		this.leDomicile = leDomicile;
	}

	public java.lang.String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(java.lang.String documentName) {
		this.documentName = documentName;
	}

	public java.lang.String getDocumentDesc() {
		return this.documentDesc;
	}

	public void setDocumentDesc(java.lang.String documentDesc) {
		this.documentDesc = documentDesc;
	}

	public java.lang.String getDocumentCertification() {
		return this.documentCertification;
	}

	public void setDocumentCertification(java.lang.String documentCertification) {
		this.documentCertification = documentCertification;
	}

	public java.lang.String getDocumentPolicy() {
		return this.documentPolicy;
	}

	public void setDocumentPolicy(java.lang.String documentPolicy) {
		this.documentPolicy = documentPolicy;
	}

	public java.lang.String getInstructions() {
		return this.instructions;
	}

	public void setInstructions(java.lang.String instructions) {
		this.instructions = instructions;
	}

	public java.lang.String getDocumentTemplate() {
		return this.documentTemplate;
	}

	public void setDocumentTemplate(java.lang.String documentTemplate) {
		this.documentTemplate = documentTemplate;
	}

	public java.lang.String getDocumentGroup() {
		return this.documentGroup;
	}

	public void setDocumentGroup(java.lang.String documentGroup) {
		this.documentGroup = documentGroup;
	}

	public criteriaASIC(java.lang.String product, java.lang.String subProduct,
			java.lang.String service, java.lang.String subService,
			java.lang.String region, java.lang.String country,
			java.lang.String audience, java.lang.String subChannel,
			java.lang.String residency, java.lang.String entityTypes,
			java.lang.String leDomicile, java.lang.String documentName,
			java.lang.String documentDesc,
			java.lang.String documentCertification,
			java.lang.String documentPolicy, java.lang.String instructions,
			java.lang.String documentTemplate, java.lang.String documentGroup) {
		this.product = product;
		this.subProduct = subProduct;
		this.service = service;
		this.subService = subService;
		this.region = region;
		this.country = country;
		this.audience = audience;
		this.subChannel = subChannel;
		this.residency = residency;
		this.entityTypes = entityTypes;
		this.leDomicile = leDomicile;
		this.documentName = documentName;
		this.documentDesc = documentDesc;
		this.documentCertification = documentCertification;
		this.documentPolicy = documentPolicy;
		this.instructions = instructions;
		this.documentTemplate = documentTemplate;
		this.documentGroup = documentGroup;
	}

}