package com.myspace.documentgenerator;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class documentResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String documentName;
	private java.lang.String description;
	private java.lang.String instructions;
	private java.lang.String template;
	private java.lang.String certification;
	private java.lang.String policy;
	private java.lang.String checklistNote;
	private java.lang.String documentCategory;

	public documentResult() {
	}

	public java.lang.String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(java.lang.String documentName) {
		this.documentName = documentName;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getInstructions() {
		return this.instructions;
	}

	public void setInstructions(java.lang.String instructions) {
		this.instructions = instructions;
	}

	public java.lang.String getTemplate() {
		return this.template;
	}

	public void setTemplate(java.lang.String template) {
		this.template = template;
	}

	public java.lang.String getCertification() {
		return this.certification;
	}

	public void setCertification(java.lang.String certification) {
		this.certification = certification;
	}

	public java.lang.String getPolicy() {
		return this.policy;
	}

	public void setPolicy(java.lang.String policy) {
		this.policy = policy;
	}

	public java.lang.String getChecklistNote() {
		return this.checklistNote;
	}

	public void setChecklistNote(java.lang.String checklistNote) {
		this.checklistNote = checklistNote;
	}

	public java.lang.String getDocumentCategory() {
		return this.documentCategory;
	}

	public void setDocumentCategory(java.lang.String documentCategory) {
		this.documentCategory = documentCategory;
	}

	public documentResult(java.lang.String documentName,
			java.lang.String description, java.lang.String instructions,
			java.lang.String template, java.lang.String certification,
			java.lang.String policy, java.lang.String checklistNote,
			java.lang.String documentCategory) {
		this.documentName = documentName;
		this.description = description;
		this.instructions = instructions;
		this.template = template;
		this.certification = certification;
		this.policy = policy;
		this.checklistNote = checklistNote;
		this.documentCategory = documentCategory;
	}

}