package com.myspace.documentgenerator;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String documentName;
	private java.lang.String documentDescription;
	private java.lang.String documentCertification;
	private java.lang.String documentPolicy;
	private java.lang.String clientInstr;

	public DocumentResult() {
	}

	public java.lang.String getDocumentName() {
		return this.documentName;
	}

	public void setDocumentName(java.lang.String documentName) {
		this.documentName = documentName;
	}

	public java.lang.String getDocumentDescription() {
		return this.documentDescription;
	}

	public void setDocumentDescription(java.lang.String documentDescription) {
		this.documentDescription = documentDescription;
	}

	public java.lang.String getDocumentCertification() {
		return this.documentCertification;
	}

	public void setDocumentCertification(java.lang.String documentCertification) {
		this.documentCertification = documentCertification;
	}

	public java.lang.String getDocumentPolicy() {
		return this.documentPolicy;
	}

	public void setDocumentPolicy(java.lang.String documentPolicy) {
		this.documentPolicy = documentPolicy;
	}

	public java.lang.String getClientInstr() {
		return this.clientInstr;
	}

	public void setClientInstr(java.lang.String clientInstr) {
		this.clientInstr = clientInstr;
	}

	public DocumentResult(java.lang.String documentName,
			java.lang.String documentDescription,
			java.lang.String documentCertification,
			java.lang.String documentPolicy, java.lang.String clientInstr) {
		this.documentName = documentName;
		this.documentDescription = documentDescription;
		this.documentCertification = documentCertification;
		this.documentPolicy = documentPolicy;
		this.clientInstr = clientInstr;
	}

}