package com.myspace.documentgenerator;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentConf implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String product;

	@org.kie.api.definition.type.Label(value = "clientAction")
	private java.lang.String clientAction;

	private java.lang.String clientActionSubType;

	private java.lang.String channel;

	private java.lang.String audience;

	private java.lang.String region;

	private java.lang.String country;

	private java.lang.String residency;

	private java.lang.String entityType;

	private java.lang.String domicileCountry;

	public DocumentConf() {
	}

	public java.lang.String getProduct() {
		return this.product;
	}

	public void setProduct(java.lang.String product) {
		this.product = product;
	}

	public java.lang.String getClientAction() {
		return this.clientAction;
	}

	public void setClientAction(java.lang.String clientAction) {
		this.clientAction = clientAction;
	}

	public java.lang.String getClientActionSubType() {
		return this.clientActionSubType;
	}

	public void setClientActionSubType(java.lang.String clientActionSubType) {
		this.clientActionSubType = clientActionSubType;
	}

	public java.lang.String getChannel() {
		return this.channel;
	}

	public void setChannel(java.lang.String channel) {
		this.channel = channel;
	}

	public java.lang.String getAudience() {
		return this.audience;
	}

	public void setAudience(java.lang.String audience) {
		this.audience = audience;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getResidency() {
		return this.residency;
	}

	public void setResidency(java.lang.String residency) {
		this.residency = residency;
	}

	public java.lang.String getEntityType() {
		return this.entityType;
	}

	public void setEntityType(java.lang.String entityType) {
		this.entityType = entityType;
	}

	public java.lang.String getDomicileCountry() {
		return this.domicileCountry;
	}

	public void setDomicileCountry(java.lang.String domicileCountry) {
		this.domicileCountry = domicileCountry;
	}

	public DocumentConf(java.lang.String product,
			java.lang.String clientAction,
			java.lang.String clientActionSubType, java.lang.String channel,
			java.lang.String audience, java.lang.String region,
			java.lang.String country, java.lang.String residency,
			java.lang.String entityType, java.lang.String domicileCountry) {
		this.product = product;
		this.clientAction = clientAction;
		this.clientActionSubType = clientActionSubType;
		this.channel = channel;
		this.audience = audience;
		this.region = region;
		this.country = country;
		this.residency = residency;
		this.entityType = entityType;
		this.domicileCountry = domicileCountry;
	}

}