package com.myspace.documentgenerator;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResultList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.documentgenerator.criteria> criteria;

	public ResultList() {
	}

	public java.util.List<com.myspace.documentgenerator.criteria> getCriteria() {
		return this.criteria;
	}

	public void setCriteria(
			java.util.List<com.myspace.documentgenerator.criteria> criteria) {
		this.criteria = criteria;
	}

	public ResultList(
			java.util.List<com.myspace.documentgenerator.criteria> criteria) {
		this.criteria = criteria;
	}

}